// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecursosHumanos.API.Data;

#nullable disable

namespace RecursosHumanos.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecursosHumanos.API.Models.Gender", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Code = "M",
                            Description = "Masculino"
                        },
                        new
                        {
                            Code = "F",
                            Description = "Femenino"
                        },
                        new
                        {
                            Code = "N",
                            Description = "No Binario"
                        });
                });

            modelBuilder.Entity("RecursosHumanos.API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GenderCode");

                    b.HasIndex("StatusCode");

                    b.ToTable("People");
                });

            modelBuilder.Entity("RecursosHumanos.API.Models.Status", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Code = "A",
                            Description = "Activo"
                        },
                        new
                        {
                            Code = "I",
                            Description = "Inactivo"
                        });
                });

            modelBuilder.Entity("RecursosHumanos.API.Models.Person", b =>
                {
                    b.HasOne("RecursosHumanos.API.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecursosHumanos.API.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
